<script setup lang="ts">
definePageMeta({ roles: ['ADMIN'] })
const { request } = useApiClient(); const toast = useToast(); const busy = ref('')
const lecturer = reactive({ email: '', employeeCode: '', firstNameTh: '', lastNameTh: '', phone: '' })
const template = reactive({ code: '', subject: 'STUDENT', name: '', itemsJson: '[{"code":"ITEM_1","label":"หัวข้อประเมิน","answerType":"SCORE","required":true,"maxScore":5,"weight":1}]' })
const activation = reactive({ userId: '', reason: '' })
const accountCommand = reactive({ userId: '', command: 'password-reset', reason: '' })
const publication = reactive({ versionId: '' })
function optional(value: string) { return value.trim() || undefined }
async function createLecturer() { busy.value = 'lecturer'; try { const result = await request('/api/admin/users', { method: 'POST', body: { email: lecturer.email.trim(), firstNameTh: lecturer.firstNameTh.trim(), lastNameTh: lecturer.lastNameTh.trim(), employeeCode: optional(lecturer.employeeCode), phone: optional(lecturer.phone) } }); toast.add({ title: 'สร้างบัญชีอาจารย์แล้ว', description: JSON.stringify(result), color: 'primary' }) } catch (cause) { toast.add({ title: 'สร้างบัญชีไม่สำเร็จ', description: cause instanceof Error ? cause.message : 'โปรดลองใหม่', color: 'error' }) } finally { busy.value = '' } }
async function createTemplate() { busy.value = 'template'; try { const items = JSON.parse(template.itemsJson); const result = await request('/api/evaluation-templates', { method: 'POST', body: { code: template.code.trim(), subject: template.subject, name: template.name.trim(), items } }); toast.add({ title: 'สร้าง Template แล้ว', description: JSON.stringify(result), color: 'primary' }) } catch (cause) { toast.add({ title: 'สร้าง Template ไม่สำเร็จ', description: cause instanceof Error ? cause.message : 'ตรวจสอบ JSON', color: 'error' }) } finally { busy.value = '' } }
async function issueActivation() { busy.value = 'activation'; try { const result = await request(`/api/admin/users/${activation.userId}/activation-code`, { method: 'POST', body: { reason: activation.reason.trim() } }); toast.add({ title: 'สร้าง Activation Code แล้ว', description: JSON.stringify(result), color: 'primary' }) } catch (cause) { toast.add({ title: 'สร้าง Code ไม่สำเร็จ', description: cause instanceof Error ? cause.message : 'โปรดลองใหม่', color: 'error' }) } finally { busy.value = '' } }
async function runAccountCommand() { busy.value = 'account'; try { const result = await request(`/api/admin/users/${accountCommand.userId}/${accountCommand.command}`, { method: 'POST', body: { reason: accountCommand.reason.trim() } }); toast.add({ title: 'ดำเนินการบัญชีแล้ว', description: JSON.stringify(result), color: 'primary' }) } catch (cause) { toast.add({ title: 'ดำเนินการบัญชีไม่สำเร็จ', description: cause instanceof Error ? cause.message : 'โปรดลองใหม่', color: 'error' }) } finally { busy.value = '' } }
async function publishTemplate() { busy.value = 'publish'; try { const result = await request(`/api/evaluation-templates/versions/${publication.versionId}/publish`, { method: 'POST', body: { expectedStatus: 'DRAFT' } }); toast.add({ title: 'เผยแพร่ Template Version แล้ว', description: JSON.stringify(result), color: 'primary' }) } catch (cause) { toast.add({ title: 'เผยแพร่ไม่สำเร็จ', description: cause instanceof Error ? cause.message : 'โปรดลองใหม่', color: 'error' }) } finally { busy.value = '' } }
</script>
<template><div><PageHeader title="จัดการระบบ" description="บัญชีอาจารย์ Activation และ Evaluation Template" icon="i-lucide-settings-2" />
  <div class="grid gap-5 xl:grid-cols-2">
    <form class="space-y-3 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900" @submit.prevent="createLecturer"><h2 class="font-semibold">สร้างบัญชีอาจารย์</h2><input v-model="lecturer.email" required type="email" autocomplete="email" placeholder="อีเมลสำหรับเข้าสู่ระบบ" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><div class="grid gap-3 sm:grid-cols-2"><input v-model="lecturer.firstNameTh" required placeholder="ชื่อ" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><input v-model="lecturer.lastNameTh" required placeholder="นามสกุล" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><input v-model="lecturer.employeeCode" placeholder="รหัสพนักงาน" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><input v-model="lecturer.phone" placeholder="โทรศัพท์" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"></div><UButton type="submit" :loading="busy === 'lecturer'" label="สร้างบัญชี" /></form>
    <form class="space-y-3 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900" @submit.prevent="issueActivation"><h2 class="font-semibold">ออก Activation Code</h2><input v-model="activation.userId" required placeholder="User ID" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><textarea v-model="activation.reason" required minlength="3" rows="3" placeholder="เหตุผล" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent p-3 dark:border-slate-700" /><UButton type="submit" :loading="busy === 'activation'" label="สร้าง Code" /></form>
    <form class="space-y-3 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900" @submit.prevent="runAccountCommand"><h2 class="font-semibold">คำสั่งบัญชีผู้ใช้</h2><input v-model="accountCommand.userId" required placeholder="User ID" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><select v-model="accountCommand.command" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><option value="password-reset">ออก Password Reset</option><option value="suspend">ระงับบัญชี</option><option value="reactivate">เปิดใช้งานอีกครั้ง</option></select><textarea v-model="accountCommand.reason" required minlength="3" rows="3" placeholder="เหตุผล" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent p-3 dark:border-slate-700" /><UButton type="submit" :loading="busy === 'account'" label="ยืนยันคำสั่ง" /></form>
    <form class="space-y-3 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900" @submit.prevent="publishTemplate"><h2 class="font-semibold">เผยแพร่ Template Version</h2><input v-model="publication.versionId" required placeholder="Template Version ID" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><UButton type="submit" :loading="busy === 'publish'" label="เผยแพร่ DRAFT" /></form>
    <form class="space-y-3 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900 xl:col-span-2" @submit.prevent="createTemplate"><h2 class="font-semibold">สร้าง Evaluation Template</h2><div class="grid gap-3 sm:grid-cols-3"><input v-model="template.code" required placeholder="Template Code" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><select v-model="template.subject" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><option value="STUDENT">STUDENT</option><option value="ORGANIZATION">ORGANIZATION</option></select><input v-model="template.name" required placeholder="ชื่อแบบประเมิน" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"></div><textarea v-model="template.itemsJson" required rows="7" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent p-3 font-mono text-sm dark:border-slate-700" /><UButton type="submit" :loading="busy === 'template'" label="สร้าง Template Version 1" /></form>
  </div></div></template>
