<script setup lang="ts">
definePageMeta({ roles: ['STUDENT', 'LECTURER', 'ADMIN'] })
const { request } = useApiClient(); const toast = useToast(); const busy = ref(false)
const { user } = useSession()
const route = useRoute()
const mode = ref<'batch' | 'member' | 'removeMember' | 'revision' | 'batchSend' | 'send' | 'delivery' | 'assignment' | 'acknowledge' | 'assignOwner'>('send')
const form = reactive({ batchId: '', deliveryId: '', memberId: '', coopTermId: '', workSiteId: '', documentType: 'COOP_REQUEST', requestId: '', expectedVersion: '1', kind: 'LETTER', reason: '', documentNo: '', documentYear: String(new Date().getFullYear() + 543), documentDate: '', ownerType: 'STUDENT', ownerUserId: '', channel: '', recipient: '', sentAt: '', acknowledgedAt: '' })
const file = ref<File | null>(null)
onMounted(() => {
  if (typeof route.query.mode === 'string' && ['batch', 'member', 'removeMember', 'revision', 'batchSend', 'send', 'delivery', 'assignment', 'acknowledge', 'assignOwner'].includes(route.query.mode)) mode.value = route.query.mode as typeof mode.value
  for (const key of ['batchId', 'deliveryId', 'requestId', 'expectedVersion'] as const) if (typeof route.query[key] === 'string') form[key] = route.query[key]
})
async function upload() { if (!file.value) throw new Error('กรุณาเลือกไฟล์'); const data = new FormData(); data.append('file', file.value); return await request<{ fileVersionId: string }>('/api/files', { method: 'POST', body: data }) }
async function submit() {
  busy.value = true
  try {
    let result: unknown
    if (mode.value === 'batch') result = await request('/api/document-batches', { method: 'POST', body: { coopTermId: form.coopTermId.trim(), workSiteId: form.workSiteId.trim(), documentType: form.documentType.trim() } })
    else if (mode.value === 'member') result = await request(`/api/document-batches/${form.batchId}/add-member`, { method: 'POST', body: { requestId: form.requestId.trim(), expectedBatchVersion: Number(form.expectedVersion) } })
    else if (mode.value === 'removeMember') result = await request(`/api/document-batches/${form.batchId}/remove-member`, { method: 'POST', body: { memberId: form.memberId.trim(), expectedBatchVersion: Number(form.expectedVersion), reason: form.reason.trim() } })
    else if (mode.value === 'revision') { const stored = await upload(); result = await request(`/api/document-batches/${form.batchId}/revisions`, { method: 'POST', body: { fileVersionId: stored.fileVersionId, kind: form.kind, ...(form.reason.trim() ? { reason: form.reason.trim() } : {}) } }) }
    else if (mode.value === 'batchSend') result = await request(`/api/document-batches/${form.batchId}/send`, { method: 'POST', body: { expectedVersion: Number(form.expectedVersion), documentNo: form.documentNo.trim(), documentYear: Number(form.documentYear), documentDate: form.documentDate } })
    else if (mode.value === 'assignment') result = await request(`/api/document-batches/${form.batchId}/delivery-assignment`, { method: 'POST', body: { ownerType: form.ownerType, ownerUserId: form.ownerUserId.trim(), reason: form.reason.trim() } })
    else if (mode.value === 'delivery' || mode.value === 'send') {
      const evidenceFileVersionId = file.value ? (await upload()).fileVersionId : undefined
      result = mode.value === 'send'
        ? await request(`/api/deliveries/${form.deliveryId}/send`, { method: 'POST', body: { channel: form.channel.trim(), recipient: form.recipient.trim(), sentAt: new Date(form.sentAt).toISOString(), ...(form.reason.trim() ? { note: form.reason.trim() } : {}), ...(evidenceFileVersionId ? { evidenceFileVersionId } : {}) } })
        : await request(`/api/document-batches/${form.batchId}/deliveries`, { method: 'POST', body: { ownerType: form.ownerType, ownerUserId: form.ownerUserId.trim(), channel: form.channel.trim(), recipient: form.recipient.trim(), sentAt: new Date(form.sentAt).toISOString(), ...(form.reason.trim() ? { note: form.reason.trim() } : {}), ...(evidenceFileVersionId ? { evidenceFileVersionId } : {}) } })
    } else if (mode.value === 'acknowledge') result = await request(`/api/deliveries/${form.deliveryId}/acknowledge`, { method: 'POST', body: { acknowledgedAt: new Date(form.acknowledgedAt).toISOString(), ...(form.reason.trim() ? { note: form.reason.trim() } : {}) } })
    else result = await request(`/api/deliveries/${form.deliveryId}/assign-owner`, { method: 'POST', body: { ownerType: form.ownerType, ownerUserId: form.ownerUserId.trim(), reason: form.reason.trim() } })
    toast.add({ title: 'ดำเนินการสำเร็จ', description: JSON.stringify(result), color: 'primary' })
  } catch (cause) { toast.add({ title: 'ดำเนินการไม่สำเร็จ', description: cause instanceof Error ? cause.message : 'โปรดลองใหม่', color: 'error' }) } finally { busy.value = false }
}
</script>
<template><div class="max-w-4xl"><PageHeader title="จัดการชุดเอกสาร" description="สร้างชุด เพิ่มสมาชิก เพิ่ม revision ส่งเอกสาร และบันทึกการส่ง" icon="i-lucide-folder-cog" />
  <form class="space-y-5 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900" @submit.prevent="submit">
    <UButton v-if="user?.role !== 'STUDENT'" type="button" color="error" variant="outline" icon="i-lucide-user-minus" label="นำสมาชิกออกจากชุดร่าง" @click="mode = 'removeMember'" />
    <label class="block"><span class="mb-1 block text-sm font-medium">คำสั่ง</span><select v-model="mode" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><option v-if="user?.role !== 'STUDENT'" value="batch">สร้างชุด</option><option v-if="user?.role !== 'STUDENT'" value="member">เพิ่มสมาชิก</option><option v-if="user?.role !== 'STUDENT'" value="revision">เพิ่ม revision</option><option v-if="user?.role !== 'STUDENT'" value="batchSend">ออกและส่งชุดเอกสาร</option><option v-if="user?.role !== 'STUDENT'" value="delivery">บันทึกการส่งแทน</option><option v-if="user?.role !== 'STUDENT'" value="assignment">มอบหมายผู้นำส่ง</option><option value="send">บันทึกว่าส่งแล้ว</option><option value="acknowledge">ยืนยันการส่ง</option><option v-if="user?.role !== 'STUDENT'" value="assignOwner">เปลี่ยนผู้รับผิดชอบ</option></select></label>
    <div class="grid gap-4 sm:grid-cols-2">
      <template v-if="mode === 'batch'"><LookupSelect v-model="form.coopTermId" resource="COOP_TERMS" label="ภาคสหกิจ" required /><LookupSelect v-model="form.workSiteId" resource="WORK_SITES" label="สถานที่ปฏิบัติงาน" required /><input v-model="form.documentType" required placeholder="Document Type" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"></template>
      <template v-else-if="!['acknowledge', 'assignOwner', 'send'].includes(mode)"><LookupSelect v-model="form.batchId" resource="DOCUMENT_BATCHES" label="ชุดเอกสาร" required /></template>
      <template v-else><LookupSelect v-model="form.deliveryId" resource="DELIVERIES" label="รายการนำส่ง" required /></template>
      <template v-if="mode === 'member'"><input v-model="form.requestId" required placeholder="Request ID" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><input v-model="form.expectedVersion" required type="number" min="1" placeholder="Version" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"></template>
      <template v-if="mode === 'removeMember'"><input v-model="form.memberId" required placeholder="Member ID" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><input v-model="form.expectedVersion" required type="number" min="1" placeholder="Version" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><input v-model="form.reason" required minlength="3" placeholder="เหตุผลที่นำออก" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"></template>
      <template v-if="mode === 'revision'"><select v-model="form.kind" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><option value="LETTER">LETTER</option><option value="BLANK_RESPONSE">BLANK_RESPONSE</option></select><input type="file" required accept=".pdf" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700" @change="file = ($event.target as HTMLInputElement).files?.[0] || null"><input v-model="form.reason" placeholder="เหตุผลเมื่อแก้ไขหลังส่ง" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"></template>
      <template v-if="mode === 'batchSend'"><input v-model="form.expectedVersion" required type="number" min="1" placeholder="Version" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><input v-model="form.documentNo" required placeholder="เลขหนังสือ" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><input v-model="form.documentYear" required type="number" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><input v-model="form.documentDate" required type="date" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"></template>
      <template v-if="mode === 'delivery'"><select v-model="form.ownerType" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><option value="STUDENT">STUDENT</option><option value="LECTURER">LECTURER</option></select><LookupSelect v-model="form.ownerUserId" :resource="form.ownerType === 'STUDENT' ? 'STUDENT_TERMS' : 'LECTURERS'" value-key="userId" label="ผู้รับผิดชอบการนำส่ง" required /><input v-model="form.channel" required placeholder="ช่องทาง" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><input v-model="form.recipient" required placeholder="ผู้รับ" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><input v-model="form.sentAt" required type="datetime-local" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><input type="file" accept=".pdf" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700" @change="file = ($event.target as HTMLInputElement).files?.[0] || null"><input v-model="form.reason" placeholder="หมายเหตุ" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"></template>
      <template v-if="mode === 'assignment'"><select v-model="form.ownerType" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><option value="STUDENT">STUDENT</option><option value="LECTURER">LECTURER</option></select><LookupSelect v-model="form.ownerUserId" :resource="form.ownerType === 'STUDENT' ? 'STUDENT_TERMS' : 'LECTURERS'" value-key="userId" label="ผู้รับผิดชอบการนำส่ง" required /><input v-model="form.reason" required minlength="3" placeholder="เหตุผลการมอบหมาย" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"></template>
      <template v-if="mode === 'send'"><input v-model="form.channel" required placeholder="ช่องทาง" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><input v-model="form.recipient" required placeholder="ผู้รับ" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><input v-model="form.sentAt" required type="datetime-local" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><input type="file" accept=".pdf" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700" @change="file = ($event.target as HTMLInputElement).files?.[0] || null"><input v-model="form.reason" placeholder="หมายเหตุ" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"></template>
      <template v-if="mode === 'acknowledge'"><input v-model="form.acknowledgedAt" required type="datetime-local" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><input v-model="form.reason" placeholder="หมายเหตุ" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"></template>
      <template v-if="mode === 'assignOwner'"><select v-model="form.ownerType" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"><option value="STUDENT">STUDENT</option><option value="LECTURER">LECTURER</option></select><LookupSelect v-model="form.ownerUserId" :resource="form.ownerType === 'STUDENT' ? 'STUDENT_TERMS' : 'LECTURERS'" value-key="userId" label="ผู้รับผิดชอบการนำส่ง" required /><input v-model="form.reason" required placeholder="เหตุผลการเปลี่ยนผู้รับผิดชอบ" class="min-h-11 w-full rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700"></template>
    </div><div class="flex justify-end"><UButton type="submit" :loading="busy" label="ยืนยันคำสั่ง" /></div>
  </form></div></template>
